wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1637307951
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.7.11
      5: 0.12.6
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
